### ISSUE TITLE
repo size

### ISSUE THREAD

**Issue by sonoro1234** [BrutPitt/imGuIZMO.quat#3]
Hi,

I am concerned with the repo size in case I add it as a submodule:

The whole LuaJIT-ImGui repo (with cimgui and imgui as submodules) has 67.6 Mb (where only 9.64 Mb are from code and the rest from .git folder)

In imGuiZMO.quat with only 100 Kb needed, the whole repo has 82.3 Mb (with 24.5 Mb from the .git folder)

Not being a git expert, I dont know if something could be done.

Thanks for you attention.

**Comment by BrutPitt** [comment]
Ciao.
Thanks to reporting it

Honestly neither am I expert of github... but just now, looking in the repository directory, I found a VStudio DB file (49MB used for debug and not necessary to project, in the in a example/vs2017 sub-sub-folder)

I'll remove it!

About .git folder...
Now I see if I can make it smaller/purge some elements (perhaps there are some olden copies of that DB file)

**Comment by sonoro1234** [comment]
Now it is much less 34 Mb!!
Althought the code is 10 Mb only, the rest is `.git` folder.
May be old VStudio DBs...?

**Comment by BrutPitt** [comment]
I'm sorry ... wait just a moment... please ;-)
I have just reduced also the .git size from 23MB to 5MB (removing internal .db cached file) ... but not still committed ... because i am trying to remove also GLM lib, no longer required: now there is the internal vgMath 
So I need just a little more time...

**Comment by BrutPitt** [comment]
Try now... corrently my local **imGuIZMO.quat.git** folder is about 8/9 MB ... 
Perhaps i can delete also cached (updated images) ... just now backup the repository and after I try also that ;)

More...
There would also be a way  of moving out the "animated-gif" from repository (about 2.6MB), and link it from an external address, also from github...

Late I try also this

**Comment by sonoro1234** [comment]
I had to delete and remove. Git refused to pull because `fatal: refusing to merge unrelated histories`
But now its 32 Mb  of which 24.2 Mb are `.git`

**Comment by BrutPitt** [comment]
Currently I reduced repository in **local** to only 2.5MB in total, moving images and live demo...
I tried a `git push --force`, but **remote** .git folder remains of 24MB... 
Now i try to resolve this last problem... if is possible...

Anyway you could use the command:
` git clone --depth 1 https://github.com/BrutPitt/imGuIZMO.quat.git`
With this `--depth 1` you clone only the last commit, and the imGuIZMO.quat repo cloning is about 4.5MB with this command

**Comment by BrutPitt** [comment]
Mission accomplished
Now with the `clone` command I downloaded only **2.4MB** (for whole repo), about 6MB on disk.

Anyway, using `clone --depth 1` it is even less: 4.5MB

I just had forgotten the `--mirror` flag when I had cloned the master repo before to shrink... so I had made the changes only locally and not on github: now should be all right

**Comment by sonoro1234** [comment]
Great!!
Completely squashed to 6 Mb!!

**Comment by sonoro1234** [comment]
Just added to LuaJIT-ImGui
Thanks again!!

**Comment by BrutPitt** [comment]
Thanks to you to add ImGuIZMO.quat

Adding... just a question
I downloaded LuaJIT-ImGui and the `extras/ImGuIZMO.quat` folder is empty.
It's normal?
(also from github webPage it is empty... but I still have to try to build it)

**Comment by sonoro1234** [comment]
I always forget things!!
.gitmodules was not set, now it is.

**Comment by BrutPitt** [comment]
No problem... you're not the only one... ;)

Now it appears.
Thanks again.

**Comment by sonoro1234** [comment]
> but I still have to try to build it)

To use imgui glfw or sdl is needed.
If you want to try it better build https://github.com/sonoro1234/anima which has LuaJIT-ImGui but also LuaJIT-GLFW. 
Please tell me if you have any problem!!
