### ISSUE TITLE
Build error with VGIZMO_USES_GLM - GCC/MinGW (imGuIZMO.quat v3.0)

### ISSUE THREAD

**Issue by moritz-h** [BrutPitt/imGuIZMO.quat#4]
I get the following build error if setting `#define VGIZMO_USES_GLM`
vGizmo.h:487:9: error: ‘tbActive’ was not declared in this scope

**Comment by BrutPitt** [comment]
Hi.

Thanks for reporting and sorry for inconvenience.
I had posted commit just last night (not yet as official release) and hadn't tested with gcc yet (only MSVC and CLang): it's more rigorous with parent members.

https://github.com/BrutPitt/imGuIZMO.quat/commit/a46867bb1f3a9b59fc7f25613ed7abad1db4d220#diff-e9e919361c4d193bca672a3b4465d755

Now it should be fine.
Thanks again and let me know.

**Comment by BrutPitt** [comment]
I guess it works, now.
I close the issue...
